#!/bin/bash

if [ -z `git config --global --get github.user` ] ; then
    gh_user=`git remote -v | grep push | sed -e 's/.\+://g' -e 's/\/.\+//g'`
else
    gh_user=`git config --global --get github.user`
fi

sed -i "s/\(github.com\/\)\\S\+\(\/\)/\1$gh_user\2/g" git-achievements

if [ ! -f "$HOME/.bashrc" ] ; then
    touch "$HOME/.bashrc"
fi

if [ `grep -c "PATH.*$(pwd)" "$HOME/.bashrc"` == 0 ] ; then
    echo >> "$HOME/.bashrc"
    ga_path=`pwd | sed 's/ /\\ /g'`
    echo "export PATH=\$PATH:$ga_path" >> "$HOME/.bashrc"
fi

if [ `grep -c "alias.*git-achievements'" "$HOME/.bashrc"` == 0 ] ; then
    echo "alias git='git-achievements'" >> "$HOME/.bashrc"
fi

. "$HOME/.bashrc"

git config --global achievement.upload true

